### ISSUE TITLE
Lobster fails to show connections when started from a different context via cmd

### ISSUE THREAD

**Issue by Vegemash** [marshl/Lobster#102]
Start lobster via the command line from somewhere other than the lobster folder. Create a connection or add an existing connection. It wont show up and  lobster will crash when you exit

**Comment by marshl** [comment]
Most likely caused by the message file being created in a relative path. All file loading and creating (including the xml schemas) should be found relative to the binary location.

**Comment by marshl** [comment]
@Vegemash  You can get around this by specifying the startup directory when starting Lobster. For example
```batch
start /D D:\Users\username\bin\Lobster D:\Users\username\Lobster\Lobster.exe
```
