### ISSUE TITLE
Updating a file in SVN that results in a conflict causes a crash

### ISSUE THREAD

**Issue by apigram** [marshl/Lobster#121]
Updated a file in SVN with a known conflict, got conflicts and Lobster crashed as a result. Is this intentional or should it be handled more gracefully?

**Comment by apigram** [comment]
This also appears to be happening on a regular SVN update. I don't know if perhaps its tied to when new files are added that would be picked up by Lobster automatically or now.

**Comment by marshl** [comment]
@apigram The issue should now be fixed. The change to prevent an unsynchronised file from being pushed when updated caused a crash to occur when a file is updated then deleted on slow machines.
