### ISSUE TITLE
Make lobster multi component table aware

### ISSUE THREAD

**Issue by mleonard87** [marshl/Lobster#27]
Currently Lobster tries to indicate if a file is in sync with the database. Im getting a case where lots of file say they are local only because they do not exist in my target fox_components_fox5 table. They do however exist in fox_components_env.

The fox engine is configured to read from both of these tables with fox_components_fox5.

**Comment by marshl** [comment]
To achieve this, the ClobType Xml will have to store a list of tables, the user will have be prompted which table they want to insert into for files that aren't synced, and syncing files will have to query all tables in the list.

**Comment by marshl** [comment]
Multi-table clob types are now handled in Release 9, but has not been sufficiently tested.
