### ISSUE TITLE
Lack of Tolkien Quotes

### ISSUE THREAD

**Issue by marshl** [marshl/Lobster#84]
Many files do not have a suitable Tolkien quote at the top. THIS IS UNACCEPTABLE.

**Comment by marshl** [comment]
Fixed;

**Comment by Vegemash** [comment]
README.md has no Tolkien quote

**Comment by marshl** [comment]
@Vegemash 
README.md is now fixed in the development branch

**Comment by marshl** [comment]
@Vegemash I've removed the quote from the readme file again. I think it might have been a bit confusing (and doesn't really make sense for anyone that hasn't used Clobber)
